### ISSUE TITLE
Faces firmware for on screen repl

### ISSUE THREAD

**Issue by machinehistories** [m5stack/FACES-Firmware#2]
I just purchased the faces M5stack and I wanted to know what is the micropython firmware that comes loaded on the board. It has an on screen repl shell that is displayed on the m5stack screen. If I try out some of the arduino example files which micropython firmware do I use to get the board back to the original state.

**Comment by lukasmaximus89** [comment]
Hi there, sorry for the late reply. The micropython REPL firmware has been added to the repository now. It hasn't been developed in a long time and thus is lacking in many of the recent features of other M5Stack micropython builds. We hope to work with the community to develop an updated and better version of the firmware in the near future

**Comment by machinehistories** [comment]
Lukas,
   I sent this question to the tech@m5stack.com but haven't heard back yet.
Maybe you can help.I got the 6060 push and it is a beautiful little device
however I am having issues. When I plug it in I get all 4 leds flashing
twice and it almost sounds like the motor wants to step but after a few
seconds the lights go off and the sound stops. When I send a command over
rs485 I get no movement and the following message
_________________________________________________________
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
[RX]> M5Stack initializing...[RX]> [RX]> [RX]> [RX]> [RX]> [RX]> ÿ[RX]>
À[RX]> [[RX]> W[RX]> ßï[Wßï[W_Wëÿ[W÷Uëÿ[RX]> [××[RX]> Wëÿ[RX]> [×[RX]> [Wß«

Here is my arduino code:
___________________________________________________________
#include <M5Stack.h>


void setup() {

  M5.begin();

  Serial.begin(115200);

  // Serial2.begin(unsigned long baud, uint32_t config, int8_t rxPin,
int8_t txPin, bool invert)
  Serial2.begin(115200, SERIAL_8N1, 16, 17);
  Serial2.println("ID");
  Serial.write(Serial2.read());
  delay(1000);
  Serial2.println("ID=s");
  Serial.write(Serial2.read());
  delay(1000);
  Serial2.println("IDsP");
  Serial.write(Serial2.read());
  delay(1000);
}

void loop() {

 if(Serial.available()) {
   int ch = Serial.read();
   Serial2.write(ch);
 }

 if(Serial2.available()) {
   int ch = Serial2.read();
   Serial.write(ch);
 }
}
___________________________________________________________
Please let me know if I need to change the code or do I need to reflash
firmware to the mega328 or do I need another board. I can just order
another 6060 unit but I would really like to see this one move. I have a
few M5stacks with rs485 capabilities and they all produced the same
results. Also nice work on the recent tutorials. Believe it or not at the
same time you were doing the rfid sound I was working on transmitting midi
using the rfid. I am able to do it using osc. Anyways nice work. - jason

**Comment by lukasmaximus89** [comment]
Hi Jason,

Sorry to hear your issues with the 6060 and sorry we have not gotten back to you sooner.

I will check with the engineering department and see what the issue is and try and get back to you within this week.

Best Regards

Luke(M5Stack)

P.s. Better to email me at Luke@m5stack.com<mailto:Luke@m5stack.com> as I don't use this email for work.

Sent from my iPhone

On Aug 23, 2019, at 8:11 AM, machinehistories <notifications@github.com<mailto:notifications@github.com>> wrote:

Lukas,
I sent this question to the tech@m5stack.com<mailto:tech@m5stack.com> but haven't heard back yet.
Maybe you can help.I got the 6060 push and it is a beautiful little device
however I am having issues. When I plug it in I get all 4 leds flashing
twice and it almost sounds like the motor wants to step but after a few
seconds the lights go off and the sound stops. When I send a command over
rs485 I get no movement and the following message
_________________________________________________________
rst:0x1 (POWERON_RESET),boot:0x17 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:1100
load:0x40078000,len:9232
load:0x40080400,len:6400
entry 0x400806a8
[RX]> M5Stack initializing...[RX]> [RX]> [RX]> [RX]> [RX]> [RX]> ÿ[RX]>
À[RX]> [[RX]> W[RX]> ßï[Wßï[W_Wëÿ[W÷Uëÿ[RX]> [××[RX]> Wëÿ[RX]> [×[RX]> [Wß«

Here is my arduino code:
___________________________________________________________
#include <M5Stack.h>


void setup() {

M5.begin();

Serial.begin(115200);

// Serial2.begin(unsigned long baud, uint32_t config, int8_t rxPin,
int8_t txPin, bool invert)
Serial2.begin(115200, SERIAL_8N1, 16, 17);
Serial2.println("ID");
Serial.write(Serial2.read());
delay(1000);
Serial2.println("ID=s");
Serial.write(Serial2.read());
delay(1000);
Serial2.println("IDsP");
Serial.write(Serial2.read());
delay(1000);
}

void loop() {

if(Serial.available()) {
int ch = Serial.read();
Serial2.write(ch);
}

if(Serial2.available()) {
int ch = Serial2.read();
Serial.write(ch);
}
}
___________________________________________________________
Please let me know if I need to change the code or do I need to reflash
firmware to the mega328 or do I need another board. I can just order
another 6060 unit but I would really like to see this one move. I have a
few M5stacks with rs485 capabilities and they all produced the same
results. Also nice work on the recent tutorials. Believe it or not at the
same time you were doing the rfid sound I was working on transmitting midi
using the rfid. I am able to do it using osc. Anyways nice work. - jason

**Comment by machinehistories** [comment]
Ok thanks I just want to know if this is fixable or if I should just
reorder it. At this point I think the mega328 might be the problem and
maybe I shorted a few wires or something but I’m willing to try to reupload
firmware if you think it’s worth a shot otherwise I am going to get another
6060. It would be cool if I can just get a replacement board because I am
sure the stepper is fine. What would be awesome is if I have to order a new
6060push perhaps you can include a replacement board and that way I can
have two working modules. Thanks - jason

**Comment by lukasmaximus89** [comment]
Hi I presented your issue to my colleagues and they mentioned to try these changes. Make sure you are using a 24v power supply
Change the following lines in your code.
[image1.JPG]
Change baud rate to  9600， ID=123，ID should be a 3 digit number

Let me know if this helps

Sent from my iPhone

On Aug 26, 2019, at 5:13 PM, machinehistories <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok thanks I just want to know if this is fixable or if I should just
reorder it. At this point I think the mega328 might be the problem and
maybe I shorted a few wires or something but I’m willing to try to reupload
firmware if you think it’s worth a shot otherwise I am going to get another
6060. It would be cool if I can just get a replacement board because I am
sure the stepper is fine. What would be awesome is if I have to order a new
6060push perhaps you can include a replacement board and that way I can
have two working modules. Thanks - jason
